from AutoVideoMiner.app.prompt.crawler_prompts import (
    CRAWL_EXEC_PROMPT,
    MEMORY_COMPRESSION_PROMPT as CRAWLER_MEMORY_COMPRESSION_PROMPT,
    SYSTEM_PROMPT as CRAWLER_SYSTEM_PROMPT,
    TASK_CONSOLIDATION_PROMPT as CRAWLER_TASK_CONSOLIDATION_PROMPT,
)
from AutoVideoMiner.app.prompt.evaluator_prompts import (
    MEMORY_COMPRESSION_PROMPT as EVALUATOR_MEMORY_COMPRESSION_PROMPT,
    SCORING_PROMPT,
    SYSTEM_PROMPT as EVALUATOR_SYSTEM_PROMPT,
    TASK_CONSOLIDATION_PROMPT as EVALUATOR_TASK_CONSOLIDATION_PROMPT,
)
from AutoVideoMiner.app.prompt.explorer_prompts import (
    EVENT_SUMMARY_PROMPT,
    MEMORY_COMPRESSION_PROMPT as EXPLORER_MEMORY_COMPRESSION_PROMPT,
    SYSTEM_PROMPT as EXPLORER_SYSTEM_PROMPT,
    TASK_CONSOLIDATION_PROMPT as EXPLORER_TASK_CONSOLIDATION_PROMPT,
)
from AutoVideoMiner.app.prompt.planner_prompts import (
    MEMORY_COMPRESSION_PROMPT as PLANNER_MEMORY_COMPRESSION_PROMPT,
    REFLECTION_PROMPT,
    REVISION_PROMPT,
    STRATEGY_GEN_PROMPT,
    SYSTEM_PROMPT as PLANNER_SYSTEM_PROMPT,
    TASK_CONSOLIDATION_PROMPT as PLANNER_TASK_CONSOLIDATION_PROMPT,
)
from AutoVideoMiner.app.prompt.segmentation_prompts import (
    MEMORY_COMPRESSION_PROMPT as SEGMENTATION_MEMORY_COMPRESSION_PROMPT,
    SEGMENTATION_EXEC_PROMPT,
    SYSTEM_PROMPT as SEGMENTATION_SYSTEM_PROMPT,
    TASK_CONSOLIDATION_PROMPT as SEGMENTATION_TASK_CONSOLIDATION_PROMPT,
)
