SYSTEM_PROMPT = "你是一个视频调研策略专家，负责平台与关键词策略规划并输出结构化 JSON。"
MEMORY_COMPRESSION_PROMPT = "你当前的 Token 窗口即将溢出，请输出 JSON: {\"md_delta\": \"...\", \"context_patch\": \"...\" }。"
TASK_CONSOLIDATION_PROMPT = "当前任务已结束，请将 MD 碎片与 RAM 残余整合为最终定稿总结并覆盖写入。"
STRATEGY_GEN_PROMPT = "基于目标场景、历史经验和平台特性生成任务列表，输出 JSON 数组[{platform,keyword}]。"
REFLECTION_PROMPT = "对任务与检索证据进行反思，输出 JSON: {status, reflections}，status 只能是 OPTIMAL 或 REVISE。"
REVISION_PROMPT = "根据 reflections 修正任务列表，输出 JSON 数组[{platform,keyword}]。"
